import pandas as pd
from typing import TypedDict, Dict, Any
from langgraph.graph import StateGraph, END
from ..engine import compute_all_kpi
from .stockout_engine import stockout_prevention
from .deadstock_engine import deadstock_detection
from .reorder_engine import reorder_optimization

class SupplyNodeState(TypedDict):
    """
    Represents the shared state passed between nodes in the SupplyNode
    LangGraph workflow.

    The state contains the input data, KPI results, findings generated by
    each analysis engine, and the final outputs produced by the orchestrator.
    """

    # Input data
    inventory_df: Any
    suppliers_df: Any
    sales_df: Any

    # After kpi node
    kpi_results: Dict[str, Any]

    # After engines nodes
    stockout_findings: Dict[str, Any]
    deadstock_findings: Dict[str, Any]
    reorder_findings: Dict[str, Any]

    # After orchestration node
    composite_risk_score: float
    final_alert: str
    alert_metadata: Dict[str, Any]

def compute_composite_risk_score(stockout_findings: Dict[str, Any], deadstock_findings: Dict[str, Any], reorder_findings: Dict[str, Any]) -> float:
    """Compute a weighted composite risk score from engine severities."""
    severity_map = {"critical": 100, "high": 70, "medium": 40, "normal": 0}
    score = (
        severity_map.get(stockout_findings.get("severity", "normal"), 0) * 0.5 +
        severity_map.get(deadstock_findings.get("severity", "normal"), 0) * 0.3 +
        severity_map.get(reorder_findings.get("severity", "normal"), 0) * 0.2
    )
    return min(round(score, 1), 100)

def node_kpi(state: SupplyNodeState) -> SupplyNodeState:
    """
    Calculate all inventory KPIs using the input inventory, supplier,
    and sales data, and store the results in the shared state.
    """
    state["kpi_results"] = compute_all_kpi(
        state["inventory_df"],
        state["suppliers_df"], 
        state["sales_df"]
    )
    return state

def node_stockout(state: SupplyNodeState) -> SupplyNodeState:
    """
    Analyze inventory KPIs to identify SKUs at risk of stockout.

    Stores the stockout prevention engine output in the shared state.
    """
    state["stockout_findings"] = stockout_prevention(
        state["kpi_results"],
        state["inventory_df"]
    )
    return state

def node_deadstock(state: SupplyNodeState) -> SupplyNodeState:
    """
    Analyze inventory KPIs to identify dead stock and slow-moving
    inventory.

    Stores the deadstock detection engine output in the shared state.
    """
    state["deadstock_findings"] = deadstock_detection(
        state["kpi_results"],
        state["inventory_df"]
    )
    return state

def node_reorder(state: SupplyNodeState) -> SupplyNodeState:
    """
    Generate optimized reorder quantities for SKUs identified as
    critical or high risk by the stockout prevention engine.

    Stores the reorder optimization engine output in the shared state.
    """
    state["reorder_findings"] = reorder_optimization(
        state["stockout_findings"],
        state["kpi_results"], 
        state["inventory_df"], 
        state["suppliers_df"]
    )
    return state

def node_orchestrator(state: SupplyNodeState) -> SupplyNodeState:
    """
    Prepare the final orchestration outputs.

    Composite risk scoring, final alert generation, and alert metadata
    will be implemented in subsequent development stages.
    """
    state["composite_risk_score"] = compute_composite_risk_score(
        state["stockout_findings"],
        state["deadstock_findings"],
        state["reorder_findings"]
    )
    state["final_alert"] = "" # Implemented in commit 3
    state["alert_metadata"] = {} # Implemented in commit 4
    return state

# Build and compile the LangGraph agent graph
workflow = StateGraph(SupplyNodeState)
workflow.add_node("kpi", node_kpi)
workflow.add_node("stockout", node_stockout)
workflow.add_node("deadstock", node_deadstock)
workflow.add_node("reorder", node_reorder)
workflow.add_node("orchestrator", node_orchestrator)

workflow.set_entry_point("kpi")
workflow.add_edge("kpi", "stockout")
workflow.add_edge("stockout", "deadstock")
workflow.add_edge("deadstock", "reorder")
workflow.add_edge("reorder", "orchestrator")
workflow.add_edge("orchestrator", END)

app = workflow.compile()
