"""initial database schema

Revision ID: 01a173131397
Revises: 
Create Date: 2026-09-27 23:14:19.623247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a173131397'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('composite_risk_score', sa.Float(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('avg_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('minimum_order_value', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('inventory',
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('sku_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('avg_daily_demand', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('warehouse_location', sa.String(), nullable=False),
    sa.Column('last_purchase_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('opening_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index('ix_inventory_supplier_id', 'inventory', ['supplier_id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('days_of_supply', sa.Float(), nullable=False),
    sa.Column('stockout_probability', sa.Float(), nullable=False),
    sa.Column('inventory_turnover_ratio', sa.Float(), nullable=False),
    sa.Column('dead_stock_ratio', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('carrying_cost_pct', sa.Float(), nullable=False),
    sa.Column('order_fill_rate_pct', sa.Float(), nullable=True),
    sa.Column('forecast_accuracy', sa.Float(), nullable=True),
    sa.Column('economic_order_quantity', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['inventory.sku_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sku_id')
    )
    op.create_table('overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('original_recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('override_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['inventory.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_overrides_run_id', 'overrides', ['run_id'], unique=False)
    op.create_table('sales_history',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['inventory.sku_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_sales_history_sku_id', 'sales_history', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_history_sku_id', table_name='sales_history')
    op.drop_table('sales_history')
    op.drop_index('ix_overrides_run_id', table_name='overrides')
    op.drop_table('overrides')
    op.drop_table('kpi_snapshots')
    op.drop_index('ix_inventory_supplier_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('suppliers')
    op.drop_table('alerts')
    # ### end Alembic commands ###
